# AUTOGENERATED FILE. DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from .flags import Flags

from .types import *

# [Description("アクティブスキル")]
# [MessagePackObject(True)]
@dataclass
class ActiveSkillMB(MasterBookBase):
    # [Description("サブセットスキルリスト")]
    # [Nest(True, 1)]
    # [PropertyOrder(4)]
    ActiveSkillInfos: list[ActiveSkillInfo]
    # [Description("スキル名キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("ルートスキルID")]
    # [PropertyOrder(5)]
    RootActiveSkillId: int
    # [Description("初期スキルクールタイム")]
    # [PropertyOrder(2)]
    SkillInitCoolTime: int
    # [Description("スキルMAXクールタイム")]
    # [PropertyOrder(3)]
    SkillMaxCoolTime: int

# [Description("アプリバージョン")]
# [MessagePackObject(True)]
@dataclass
class AppVersionMB(MasterBookBase):
    # [Description("アプリバージョン")]
    # [PropertyOrder(2)]
    AppVersion: str
    # [Description("デバイス種別")]
    # [PropertyOrder(1)]
    DeviceType: DeviceType

# [Description("放置バトル敵データ")]
# [MessagePackObject(True)]
@dataclass
class AutoBattleEnemyMB(MasterBookBase, IBattleEnemy):
    # [Description("アクティブスキルIDのリスト")]
    # [PropertyOrder(12)]
    ActiveSkillIds: list[int]
    # [Description("ベースパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(9)]
    BaseParameter: BaseParameter
    # [Description("敵キャラクターID")]
    # [PropertyOrder(16)]
    BattleEnemyCharacterId: int
    # [Description("バトルパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(10)]
    BattleParameter: BattleParameter
    # [Description("戦闘力")]
    # [PropertyOrder(5)]
    BattlePower: int
    # [Description("レアリティ")]
    # [PropertyOrder(8)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("属性")]
    # [PropertyOrder(7)]
    ElementType: ElementType
    # [Description("敵調整ID")]
    # [PropertyOrder(18)]
    EnemyAdjustId: int
    # [Description("敵武具ID")]
    # [PropertyOrder(17)]
    EnemyEquipmentId: int
    # [Description("敵のランク")]
    # [PropertyOrder(4)]
    EnemyRank: int
    # [Description("職業")]
    # [PropertyOrder(6)]
    JobFlags: Flags[JobFlags]
    # [Description("名称キー")]
    # [PropertyOrder(3)]
    NameKey: str
    # [Description("通常攻撃として使ってくるスキルID")]
    # [PropertyOrder(11)]
    NormalSkillId: int
    # [Description("パッシブスキルIDのリスト")]
    # [PropertyOrder(13)]
    PassiveSkillIds: list[int]
    # [Description("ドロップするキャラクター経験値")]
    # [PropertyOrder(14)]
    RewardCharacterExp: int
    # [Description("ドロップするプレイヤー経験値")]
    # [PropertyOrder(15)]
    RewardPlayerExp: int
    # [Description("ユニットアイコンID")]
    # [PropertyOrder(2)]
    UnitIconId: int
    # [Description("ユニットアイコンタイプ")]
    # [PropertyOrder(1)]
    UnitIconType: UnitIconType

# [Description("バトルスケジュール")]
# [MessagePackObject(True)]
@dataclass
class BattleScheduleMB(MasterBookBase):
    # [Description("バトルタイプ")]
    # [PropertyOrder(1)]
    BattleScheduleType: BattleScheduleType
    # [Description("最大クエストID")]
    # [PropertyOrder(2)]
    MaxQuestId: int
    # [DateTimeString]
    # [Description("開始日時")]
    # [PropertyOrder(3)]
    StartTimeFixJST: str

# [Description("バトルスキル演出設定")]
# [MessagePackObject(True)]
@dataclass
class BattleSkillCharacterSettingMB(MasterBookBase):
    # [Description("文字背景色タイプ")]
    # [PropertyOrder(2)]
    CharacterColorType: CharacterColorType
    # [Description("キャラID (CharacterMB)")]
    # [PropertyOrder(1)]
    CharacterId: int

# [Description("バトルスキル演出設定")]
# [MessagePackObject(True)]
@dataclass
class BattleSkillNameSettingMB(MasterBookBase):
    # [Description("アクティブスキルID(ActiveSkillMB)")]
    # [PropertyOrder(1)]
    ActiveSkillId: int
    # [Description("改行位置設定 JP")]
    # [PropertyOrder(2)]
    NewLineIndexJP: int
    # [Description("改行位置設定 KR")]
    # [PropertyOrder(2)]
    NewLineIndexKR: int
    # [Description("改行位置設定 TW")]
    # [PropertyOrder(3)]
    NewLineIndexTW: int
    # [Description("改行位置設定 US")]
    # [PropertyOrder(3)]
    NewLineIndexUS: int

# [Description("祈りの泉　ボードランク")]
# [MessagePackObject(True)]
@dataclass
class BoardRankMB(MasterBookBase):
    # [Description("必要条件リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    BoardRankConditionInfos: list[BoardRankConditionInfo]
    # [Description("開放クエスト最大レベル")]
    # [PropertyOrder(3)]
    OpenBountyQuestMaxRarity: BountyQuestRarityFlags
    # [Description("開放クエスト最低レベル")]
    # [PropertyOrder(4)]
    OpenBountyQuestMinRarity: BountyQuestRarityFlags
    # [Description("クエスト抽選リスト詳細ID")]
    # [PropertyOrder(5)]
    QuestLotteryInfoListId: int
    # [Description("ランク")]
    # [PropertyOrder(1)]
    Rank: int

# [Description("ボスデータ")]
# [MessagePackObject(True)]
@dataclass
class BossBattleEnemyMB(MasterBookBase, IBattleEnemy):
    # [Description("アクティブスキルIDのリスト")]
    # [PropertyOrder(12)]
    ActiveSkillIds: list[int]
    # [Description("ベースパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(9)]
    BaseParameter: BaseParameter
    # [Description("敵キャラID")]
    # [PropertyOrder(14)]
    BattleEnemyCharacterId: int
    # [Description("バトルパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(10)]
    BattleParameter: BattleParameter
    # [Description("戦闘力")]
    # [PropertyOrder(5)]
    BattlePower: int
    # [Description("レアリティ")]
    # [PropertyOrder(8)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("属性")]
    # [PropertyOrder(7)]
    ElementType: ElementType
    # [Description("敵調整ID")]
    # [PropertyOrder(16)]
    EnemyAdjustId: int
    # [Description("敵武具ID")]
    # [PropertyOrder(15)]
    EnemyEquipmentId: int
    # [Description("敵のランク")]
    # [PropertyOrder(4)]
    EnemyRank: int
    # [Description("職業")]
    # [PropertyOrder(6)]
    JobFlags: Flags[JobFlags]
    # [Description("名称キー")]
    # [PropertyOrder(3)]
    NameKey: str
    # [Description("通常攻撃として使ってくるスキルID")]
    # [PropertyOrder(11)]
    NormalSkillId: int
    # [Description("パッシブスキルIDのリスト")]
    # [PropertyOrder(13)]
    PassiveSkillIds: list[int]
    # [Description("ユニットアイコンID")]
    # [PropertyOrder(2)]
    UnitIconId: int
    # [Description("ユニットアイコンタイプ")]
    # [PropertyOrder(1)]
    UnitIconType: UnitIconType

# [Description("祈りの泉　イベント")]
# [MessagePackObject(True)]
@dataclass
class BountyQuestEventMB(MasterBookBase, IHasStartEndTime):
    # [Description("終了時刻")]
    # [PropertyOrder(4)]
    EndTime: str
    # [Description("イベント説明")]
    # [PropertyOrder(2)]
    EventDescriptionKey: str
    # [Description("イベント名")]
    # [PropertyOrder(1)]
    EventNameKey: str
    # [Description("報酬量の増加率(%)")]
    # [PropertyOrder(5)]
    MultipleNumber: int
    # [Description("開始時刻")]
    # [PropertyOrder(3)]
    StartTime: str
    # [Description("対象となるアイテムリスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(7)]
    TargetItemList: list[BountyQuestEventTargetItemInfo]
    # [Description("対象となる祈りの泉クエストタイプ")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    TargetQuestTypeList: list[BountyQuestEventTargetQuestTypeInfo]

# [Description("アイテム変換情報")]
# [MessagePackObject(True)]
@dataclass
class ChangeItemMB(MasterBookBase):
    # [Description("アイテム変換タイプ")]
    # [PropertyOrder(1)]
    ChangeItemType: ChangeItemType
    # [Description("変換されるアイテムリスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    ChangeItems: list[UserItem]
    # [Description("アイテムID")]
    # [PropertyOrder(3)]
    ItemId: int
    # [Description("アイテム種別")]
    # [PropertyOrder(2)]
    ItemType: ItemType
    # [Description("変換に必要な数")]
    # [PropertyOrder(4)]
    NeedCount: int

# [Description("章")]
# [MessagePackObject(True)]
@dataclass
class ChapterMB(MasterBookBase):
    # [Description("名称キー")]
    # [PropertyOrder(2)]
    NameKey: str
    # [Description("国ID")]
    # [MasterBookId(typeof)]
    # [PropertyOrder(1)]
    StateId: int
    # [Description("領地名")]
    # [PropertyOrder(4)]
    TerritoryNameKey: str
    # [Description("テキストキー")]
    # [PropertyOrder(3)]
    TextKey: str

# [Description("キャラクターボックスサイズ")]
# [MessagePackObject(True)]
@dataclass
class CharacterBoxSizeMB(MasterBookBase):
    # [Description("倉庫所持上限")]
    # [PropertyOrder(2)]
    BoxSize: int
    # [Description("レベル")]
    # [PropertyOrder(1)]
    Lv: int
    # [Description("必要仮想通貨数")]
    # [PropertyOrder(3)]
    RequiredCurrency: int

# [Description("アルカナレベル")]
# [MessagePackObject(True)]
@dataclass
class CharacterCollectionLevelMB(MasterBookBase):
    # [Description("開放後適用されるベースパラメータ")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    BaseParameterChangeInfos: list[BaseParameterChangeInfo]
    # [Description("開放後適用されるバトルパラメータ")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    BattleParameterChangeInfos: list[BattleParameterChangeInfo]
    # [Description("キャラクターレアリティ増加")]
    # [PropertyOrder(6)]
    CharacterRarityBonus: int
    # [Description("アルカナレベル解放条件")]
    # [PropertyOrder(3)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("アルカナMBのID")]
    # [PropertyOrder(1)]
    CollectionId: int
    # [Description("アルカナレベル")]
    # [PropertyOrder(2)]
    CollectionLevel: int

# [Description("アルカナ")]
# [MessagePackObject(True)]
@dataclass
class CharacterCollectionMB(MasterBookBase, IHasJstStartEndTime):
    # [Description("新アルカナの終了時間(JST)")]
    # [PropertyOrder(4)]
    EndTimeFixJST: str
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("開放に必要なキャラーIDリスト")]
    # [PropertyOrder(2)]
    RequiredCharacterIds: list[int]
    # [Description("新アルカナの開始時間(JST)")]
    # [PropertyOrder(3)]
    StartTimeFixJST: str

# [Description("アルカナ解放報酬")]
# [MessagePackObject(True)]
@dataclass
class CharacterCollectionRewardMB(MasterBookBase):
    # [Description("構成キャラ数")]
    # [PropertyOrder(1)]
    CharacterCount: int
    # [Description("アルカナが解放されるキャラレアリティ")]
    # [PropertyOrder(3)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("段階（アルカナレベル）")]
    # [PropertyOrder(2)]
    CollectionLevel: int
    # [Description("報酬アイテム")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    RewardItems: list[UserItem]

# [Description("キャラクター視聴可能ボイス")]
# [MessagePackObject(True)]
@dataclass
class CharacterDetailVoiceMB(MasterBookBase):
    # [Description("キャラクターId")]
    # [PropertyOrder(1)]
    CharacterId: int
    # [Description("キャラクターボイス分類")]
    # [PropertyOrder(4)]
    CharacterVoiceCategory: CharacterVoiceCategory
    # [Description("Path")]
    # [Nest(False, 0)]
    # [PropertyOrder(7)]
    Path: CharacterVoicePath
    # [Description("スクロールビューでの表示順（昇順）")]
    # [PropertyOrder(8)]
    SortOrder: int
    # [Description("ボイス再生時の字幕キー")]
    # [PropertyOrder(3)]
    SubtitleKey: str
    # [Description("解放条件")]
    # [PropertyOrder(5)]
    UnlockCondition: UnlockCharacterDetailVoiceType
    # [Description("クエストID")]
    # [PropertyOrder(6)]
    UnlockQuestId: int
    # [Description("ボタン表示用テキスト（解放済）キー")]
    # [PropertyOrder(2)]
    UnlockedVoiceButtonTextKey: str

# [Description("キャラクターレベル")]
# [MessagePackObject(True)]
@dataclass
class CharacterLevelMB(MasterBookBase):
    # [Description("レベル")]
    # [PropertyOrder(1)]
    Level: int
    # [Description("レベルアップ必要アイテム")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    RequiredItemList: list[UserItem]

# [Description("キャラク動画配信モード")]
# [MessagePackObject(True)]
@dataclass
class CharacterLiveModeMB(MasterBookBase):
    # [Description("終了時間(JP)")]
    # [PropertyOrder(4)]
    BgmEndTimeJP: float
    # [Description("終了時間(US)")]
    # [PropertyOrder(6)]
    BgmEndTimeUS: float
    # [Description("BGM(JP)")]
    # [PropertyOrder(1)]
    BgmPathJP: str
    # [Description("BGM(US)")]
    # [PropertyOrder(2)]
    BgmPathUS: str
    # [Description("開始時間(JP)")]
    # [PropertyOrder(3)]
    BgmStartTimeJP: float
    # [Description("開始時間(US)")]
    # [PropertyOrder(5)]
    BgmStartTimeUS: float

# [Description("キャラクター")]
# [MessagePackObject(True)]
@dataclass
class CharacterMB(MasterBookBase, IHasJstStartEndTime):
    # [Description("アクティブスキルIDのリスト")]
    # [PropertyOrder(11)]
    ActiveSkillIds: list[int]
    # [Description("潜在能力配分係数")]
    # [Nest(False, 0)]
    # [PropertyOrder(8)]
    BaseParameterCoefficient: BaseParameter
    # [Description("潜在能力配分合計係数")]
    # [PropertyOrder(9)]
    BaseParameterGrossCoefficient: int
    # [Description("二つ名タイプ")]
    # [PropertyOrder(3)]
    CharacterType: CharacterType
    # [Description("属性")]
    # [PropertyOrder(4)]
    ElementType: ElementType
    # [Description("新キャラの図鑑表示終了時間(JST)")]
    # [PropertyOrder(17)]
    EndTimeFixJST: str
    # [Description("初期バトルパラメータ")]
    # [Nest(False, 0)]
    # [PropertyOrder(7)]
    InitialBattleParameter: BattleParameter
    # [Description("アイテム時レアリティ")]
    # [PropertyOrder(15)]
    ItemRarityFlags: Flags[ItemRarityFlags]
    # [Description("職業")]
    # [PropertyOrder(5)]
    JobFlags: Flags[JobFlags]
    # [Description("名称(二つ名)キー")]
    # [PropertyOrder(2)]
    Name2Key: str
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("通常攻撃のID")]
    # [PropertyOrder(10)]
    NormalSkillId: int
    # [Description("パッシブスキルIDのリスト")]
    # [PropertyOrder(12)]
    PassiveSkillIds: list[int]
    # [Description("レアリティ")]
    # [PropertyOrder(6)]
    RarityFlags: Flags[CharacterRarityFlags]
    # [Description("解放に必要な絆の数")]
    # [PropertyOrder(13)]
    RequireFragmentCount: int
    # [Description("新キャラの図鑑表示開始時間(JST)")]
    # [PropertyOrder(16)]
    StartTimeFixJST: str

# [Description("キャラクターレアリティ係数")]
# [MessagePackObject(True)]
@dataclass
class CharacterPotentialCoefficientMB(MasterBookBase):
    # [Description("初期レアリティ")]
    # [PropertyOrder(1)]
    InitialRarityFlags: Flags[CharacterRarityFlags]
    # [Description("レアリティ係数")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    RarityCoefficientInfo: CharacterRarityCoefficientInfo
    # [Description("レアリティ")]
    # [PropertyOrder(2)]
    RarityFlags: Flags[CharacterRarityFlags]

# [Description("キャラクター潜在能力")]
# [MessagePackObject(True)]
@dataclass
class CharacterPotentialMB(MasterBookBase):
    # [Description("キャラクターレベル")]
    # [PropertyOrder(1)]
    CharacterLevel: int
    # [Description("キャラクターサブレベル")]
    # [PropertyOrder(2)]
    CharacterSubLevel: int
    # [Description("潜在能力合計値")]
    # [PropertyOrder(3)]
    TotalBaseParameter: int

# [Description("キャラクタープロフィール")]
# [MessagePackObject(True)]
@dataclass
class CharacterProfileMB(MasterBookBase):
    # [Description("誕生日")]
    # [PropertyOrder(4)]
    Birthday: int
    # [Description("血液型")]
    # [PropertyOrder(5)]
    BloodType: CharacterBloodType
    # [Description("CV(JP)キー")]
    # [PropertyOrder(10)]
    CharacterVoiceJPKey: str
    # [Description("CV(US)キー")]
    # [PropertyOrder(11)]
    CharacterVoiceUSKey: str
    # [Description("説明キー")]
    # [PropertyOrder(7)]
    DescriptionKey: str
    # [Description("専属武具の欠片ID")]
    # [PropertyOrder(6)]
    EquipmentCompositeId: int
    # [Description("新キャラ演出メッセージ2キー")]
    # [PropertyOrder(16)]
    GachaResultMessage2Key: str
    # [Description("身長")]
    # [PropertyOrder(2)]
    Height: int
    # [Description("ラメント(JP)キー")]
    # [PropertyOrder(12)]
    LamentJPKey: str
    # [Description("ラメント(US)キー")]
    # [PropertyOrder(13)]
    LamentUSKey: str
    # [Description("日本語キャラソン歌詞")]
    # [PropertyOrder(17)]
    LyricsJPKey: str
    # [Description("英語キャラソン歌詞")]
    # [PropertyOrder(18)]
    LyricsUSKey: str
    # [Description("動画配信サイトURL(JP)")]
    # [Nest(False, 0)]
    # [PropertyOrder(8)]
    MovieJpUrl: TranslatedText
    # [Description("動画配信サイトURL(JP)")]
    # [Nest(False, 0)]
    # [PropertyOrder(9)]
    MovieUsUrl: TranslatedText
    # [Description("歌手(JP)キー")]
    # [PropertyOrder(14)]
    VocalJPKey: str
    # [Description("歌手(US)キー")]
    # [PropertyOrder(15)]
    VocalUSKey: str
    # [Description("体重")]
    # [PropertyOrder(3)]
    Weight: int

# [Description("キャラクターランクアップ")]
# [MessagePackObject(True)]
@dataclass
class CharacterRankUpMaterialMB(MasterBookBase):
    # [Description("属性の分類")]
    # [PropertyOrder(1)]
    ElementClassification: ElementClassificationType
    # [Description("Material")]
    # [PropertyOrder(4)]
    MaterialRankFlags: Flags[CharacterRarityFlags]
    # [Description("Material2")]
    # [PropertyOrder(5)]
    MaterialRankSecondFlags: Flags[CharacterRarityFlags]
    # [Description("RankFlags")]
    # [PropertyOrder(3)]
    RankFlags: Flags[CharacterRarityFlags]
    # [Description("ランクアップを完了すると適用されるランク")]
    # [PropertyOrder(6)]
    RankUpResultRarityFlags: Flags[CharacterRarityFlags]
    # [Description("ランクアップ時の方法")]
    # [PropertyOrder(2)]
    UpType: RankUpType

# [Description("キャラクターリセット")]
# [MessagePackObject(True)]
@dataclass
class CharacterResetMB(MasterBookBase):
    # [Description("リセット対象のレアリティ")]
    # [PropertyOrder(2)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("リセット対象の属性の分類")]
    # [PropertyOrder(1)]
    ElementClassificationType: ElementClassificationType
    # [Description("同名のSR+のLv1キャラ返還数")]
    # [PropertyOrder(3)]
    ReturnCharacterCount: int
    # [Description("魔女の手紙返還数")]
    # [PropertyOrder(4)]
    ReturnWitchLetterCount: int

# [Description("回想テーブル")]
# [MessagePackObject(True)]
@dataclass
class CharacterStoryMB(MasterBookBase):
    # [Description("対象キャラクターID")]
    # [PropertyOrder(1)]
    CharacterId: int
    # [Description("何個目の回想か")]
    # [PropertyOrder(2)]
    EpisodeId: int
    # [Description("制限レベル")]
    # [PropertyOrder(3)]
    Level: int
    # [Description("制限レアリティ")]
    # [PropertyOrder(7)]
    RarityFlags: Flags[CharacterRarityFlags]
    # [Description("初閲覧時報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    RewardItemList: list[UserItem]
    # [Description("スキップ説明文")]
    # [PropertyOrder(6)]
    TextKey: str
    # [Description("タイトルキー")]
    # [PropertyOrder(4)]
    TitleKey: str

# [Description("コミュニティ")]
# [MessagePackObject(True)]
@dataclass
class CommunityMB(MasterBookBase):
    # [Description("地域タイプ")]
    # [PropertyOrder(1)]
    CountryCodeType: CountryCodeType
    # [Description("SNS情報リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    SnsInfoList: list[SnsInfo]

# [Description("ディープリンク")]
# [MessagePackObject(True)]
@dataclass
class DeepLinkMB(MasterBookBase):
    # [Description("遷移タイプ")]
    # [Nest(False, 0)]
    # [PropertyOrder(1)]
    TransferDetailInfo: TransferDetailInfo

# [Description("時空の洞窟 マス詳細")]
# [MessagePackObject(True)]
@dataclass
class DungeonBattleGridMB(MasterBookBase):
    # [Description("マス名キー")]
    # [PropertyOrder(1)]
    DungeonGridNameKey: str
    # [Description("マス種別")]
    # [PropertyOrder(2)]
    DungeonGridType: DungeonBattleGridType

# [Description("時空の洞窟 アシストキャラクター")]
# [MessagePackObject(True)]
@dataclass
class DungeonBattleGuestMB(MasterBookBase, IHasJstStartEndTime):
    # [Description("キャラクターID")]
    # [PropertyOrder(1)]
    CharacterId: int
    # [Description("優先出現終了時間(JST)")]
    # [PropertyOrder(4)]
    EndTimeFixJST: str
    # [Description("優先的に出現させるか")]
    # [PropertyOrder(2)]
    IsPickup: bool
    # [Description("優先出現開始時間(JST)")]
    # [PropertyOrder(3)]
    StartTimeFixJST: str

# [Description("時空の洞窟 加護")]
# [MessagePackObject(True)]
@dataclass
class DungeonBattleRelicMB(MasterBookBase):
    # [Description("戦闘力ボーナス")]
    # [PropertyOrder(4)]
    BattlePowerBonus: int
    # [Description("戦闘力ボーナス対象")]
    # [PropertyOrder(5)]
    BattlePowerBonusTargetType: DungeonBattleRelicBattlePowerBonusTargetType
    # [Description("複数所持可能有無")]
    # [PropertyOrder(6)]
    CanMultiplePossession: bool
    # [Description("説明文キー")]
    # [PropertyOrder(8)]
    DescriptionKey: str
    # [Description("レアリティ")]
    # [PropertyOrder(2)]
    DungeonRelicRarityType: DungeonBattleRelicRarityType
    # [Description("アイコンID")]
    # [PropertyOrder(9)]
    IconId: int
    # [Description("名前キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("パッシブスキルタイプ情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(7)]
    PassiveSkillTypeInfos: list[PassiveSkillTypeInfo]
    # [Description("下位ID（0の場合は直接入手可能）")]
    # [PropertyOrder(3)]
    ReinforceFrom: int

# [Description("スキル効果グループ")]
# [MessagePackObject(True)]
@dataclass
class EffectGroupMB(MasterBookBase):
    # [Description("付与者アイコンID")]
    # [PropertyOrder(6)]
    CasterIconId: int
    # [Description("付与者アイコンタイプ")]
    # [PropertyOrder(5)]
    CasterIconType: EffectGroupIconType
    # [Description("説明文キー")]
    # [PropertyOrder(2)]
    DescriptionKey: str
    # [Description("効果アイコンID")]
    # [PropertyOrder(4)]
    IconId: int
    # [Description("効果アイコンタイプ")]
    # [PropertyOrder(3)]
    IconType: EffectGroupIconType
    # [Description("強制非表示フラグ")]
    # [PropertyOrder(7)]
    IsHide: bool
    # [Description("ターン数非表示フラグ")]
    # [PropertyOrder(8)]
    IsTurnHide: bool
    # [Description("効果名キー")]
    # [PropertyOrder(1)]
    NameKey: str

# [Description("属性ボーナス")]
# [MessagePackObject(True)]
@dataclass
class ElementBonusMB(MasterBookBase):
    # [Description("増加パラメータリスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    BattleParameterChangeInfos: list[BattleParameterChangeInfo]
    # [Description("属性条件タイプ")]
    # [PropertyOrder(1)]
    ConditionType: ElementBonusConditionType
    # [Description("発動段階")]
    # [PropertyOrder(2)]
    Phase: ElementBonusPhaseType

# [Description("武具合成")]
# [MessagePackObject(True)]
@dataclass
class EquipmentCompositeMB(MasterBookBase):
    # [Description("合成した際に取得する武具ID")]
    # [PropertyOrder(1)]
    EquipmentId: int
    # [Description("レアリティ")]
    # [PropertyOrder(4)]
    ItemRarityFlags: Flags[ItemRarityFlags]
    # [Description("必要欠片数")]
    # [PropertyOrder(2)]
    RequiredFragmentCount: int
    # [Description("必要アイテム情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    RequiredItemList: list[UserItem]

# [Description("武具進化テーブル")]
# [MessagePackObject(True)]
@dataclass
class EquipmentEvolutionMB(MasterBookBase):
    # [Description("必要アイテム情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(1)]
    EquipmentEvolutionInfoList: list[EquipmentEvolutionInfo]
    # [Description("武具進化の種類")]
    # [PropertyOrder(2)]
    EvolutionType: EvolutionType

# [Description("武具専属効果")]
# [MessagePackObject(True)]
@dataclass
class EquipmentExclusiveEffectMB(MasterBookBase):
    # [Description("専属効果(BaseParameter)")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    BaseParameterChangeInfoList: list[BaseParameterChangeInfo]
    # [Description("専属効果(BattleParameter)")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    BattleParameterChangeInfoList: list[BattleParameterChangeInfo]
    # [Description("専属効果適用キャラクターID")]
    # [PropertyOrder(1)]
    CharacterId: int

# [Description("専属スキル説明文")]
# [MessagePackObject(True)]
@dataclass
class EquipmentExclusiveSkillDescriptionMB(MasterBookBase):
    # [Description("説明文1キー")]
    # [PropertyOrder(1)]
    Description1Key: str
    # [Description("説明文2キー")]
    # [PropertyOrder(2)]
    Description2Key: str
    # [Description("説明文3キー")]
    # [PropertyOrder(3)]
    Description3Key: str

# [Description("鋳造データ")]
# [MessagePackObject(True)]
@dataclass
class EquipmentForgeMB(MasterBookBase):
    # [Description("魔装ステータス")]
    # [PropertyOrder(3)]
    MatchlessSacredTreasure: bool
    # [Description("得られる鋳造値")]
    # [PropertyOrder(4)]
    PriceForForge: int
    # [Description("成功時の武具レアリティ")]
    # [PropertyOrder(2)]
    SuccessRarityFlag: EquipmentRarityFlags
    # [Description("成功率ID")]
    # [PropertyOrder(1)]
    SuccessRateId: int

# [Description("聖装テーブル")]
# [MessagePackObject(True)]
@dataclass
class EquipmentLegendSacredTreasureMB(MasterBookBase):
    # [Description("メイル：魔法クリティカル抵抗（加算式増加）")]
    # [PropertyOrder(7)]
    ArmorMagicCriticalDamageRelaxPercent: float
    # [Description("アーム：クリティカルダメージ（加算式増加）")]
    # [PropertyOrder(5)]
    GauntletCriticalDamagePercent: float
    # [Description("メット：物理クリティカル抵抗（加算式増加）")]
    # [PropertyOrder(6)]
    HelmetPhysicalCriticalDamageRelaxPercent: float
    # [Description("聖装レベル")]
    # [PropertyOrder(1)]
    Lv: int
    # [Description("必要累積経験値")]
    # [PropertyOrder(2)]
    RequiredTotalExp: int
    # [Description("ブーツ：HPドレイン（加算式増加）")]
    # [PropertyOrder(8)]
    ShoesHpDrainPercent: float
    # [Description("アクセサリー：命中（割合増加）")]
    # [PropertyOrder(4)]
    SubHitPercent: float
    # [Description("武器：攻撃力（割合増加）")]
    # [PropertyOrder(3)]
    WeaponAttackPowerPercent: float

# [Description("魔装テーブル")]
# [MessagePackObject(True)]
@dataclass
class EquipmentMatchlessSacredTreasureMB(MasterBookBase):
    # [Description("メイル：防御貫通（加算式増加）")]
    # [PropertyOrder(7)]
    ArmorDefensePenetration: int
    # [Description("アーム：魔法防御（加算式増加）")]
    # [PropertyOrder(5)]
    GauntletMagicDamageRelax: int
    # [Description("メット：クリティカル（加算式増加）")]
    # [PropertyOrder(6)]
    HelmetCritical: int
    # [Description("魔装レベル")]
    # [PropertyOrder(1)]
    Lv: int
    # [Description("必要累積経験値")]
    # [PropertyOrder(2)]
    RequiredTotalExp: int
    # [Description("ブーツ：HP（加算式増加）")]
    # [PropertyOrder(8)]
    ShoesHp: int
    # [Description("アクセサリ：物理防御（加算式増加）")]
    # [PropertyOrder(4)]
    SubPhysicalDamageRelax: int
    # [Description("武器：攻撃力（加算式増加）")]
    # [PropertyOrder(3)]
    WeaponAttackPower: int

# [Description("武具")]
# [MessagePackObject(True)]
@dataclass
class EquipmentMB(MasterBookBase):
    # [Description("付加パラメータ合計値")]
    # [PropertyOrder(10)]
    AdditionalParameterTotal: int
    # [Description("進化先武具ID")]
    # [PropertyOrder(16)]
    AfterLevelEvolutionEquipmentId: int
    # [Description("進化先レアリティ武具ID")]
    # [PropertyOrder(17)]
    AfterRarityEvolutionEquipmentId: int
    # [Description("基礎パラメータ")]
    # [Nest(False, 0)]
    # [PropertyOrder(9)]
    BattleParameterChangeInfo: BattleParameterChangeInfo
    # [Description("武具カテゴリ")]
    # [PropertyOrder(7)]
    Category: EquipmentCategory
    # [Description("合成情報ID")]
    # [PropertyOrder(19)]
    CompositeId: int
    # [Description("武具進化テーブルID")]
    # [PropertyOrder(18)]
    EquipmentEvolutionId: int
    # [Description("専属スキル説明文ID")]
    # [PropertyOrder(15)]
    EquipmentExclusiveSkillDescriptionId: int
    # [Description("鋳造ID")]
    # [PropertyOrder(21)]
    EquipmentForgeId: int
    # [Description("武具レベル")]
    # [PropertyOrder(3)]
    EquipmentLv: int
    # [Description("武具強化素材テーブルID")]
    # [PropertyOrder(12)]
    EquipmentReinforcementMaterialId: int
    # [Description("武具セットID")]
    # [PropertyOrder(13)]
    EquipmentSetId: int
    # [Description("装備可能キャラタイプ")]
    # [PropertyOrder(6)]
    EquippedJobFlags: Flags[JobFlags]
    # [Description("専属効果ID")]
    # [PropertyOrder(14)]
    ExclusiveEffectId: int
    # [Description("最初の宝石スロット解放に必要な銅貨")]
    # [PropertyOrder(23)]
    GoldRequiredToOpeningFirstSphereSlot: int
    # [Description("ロック無し鍛錬に必要な銅貨")]
    # [PropertyOrder(22)]
    GoldRequiredToTraining: int
    # [Description("アイコンID")]
    # [PropertyOrder(24)]
    IconId: int
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("装備評価")]
    # [PropertyOrder(4)]
    PerformancePoint: int
    # [Description("品質レベル")]
    # [PropertyOrder(8)]
    QualityLv: int
    # [Description("レアリティ")]
    # [PropertyOrder(2)]
    RarityFlags: Flags[EquipmentRarityFlags]
    # [Description("武具の装備枠タイプ")]
    # [PropertyOrder(5)]
    SlotType: EquipmentSlotType

# [Description("武具強化アイテムテーブル")]
# [MessagePackObject(True)]
@dataclass
class EquipmentReinforcementMaterialMB(MasterBookBase):
    # [Description("レベル毎の強化アイテムリスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(1)]
    ReinforcementMap: list[EquipmentReinforcementMaterialInfo]

# [Description("武具強化パラメータテーブル")]
# [MessagePackObject(True)]
@dataclass
class EquipmentReinforcementParameterMB(MasterBookBase):
    # [Description("強化倍率係数")]
    # [PropertyOrder(1)]
    ReinforcementCoefficient: float

# [Description("武具進化素材")]
# [MessagePackObject(True)]
@dataclass
class EquipmentSetMaterialMB(MasterBookBase):
    # [Description("説明文キー")]
    # [PropertyOrder(4)]
    DescriptionKey: str
    # [Description("表示名キー")]
    # [PropertyOrder(2)]
    DisplayNameKey: str
    # [Description("アイコンID")]
    # [PropertyOrder(5)]
    IconId: int
    # [Description("レアリティ")]
    # [PropertyOrder(7)]
    ItemRarityFlags: Flags[ItemRarityFlags]
    # [Description("レベル")]
    # [PropertyOrder(3)]
    Lv: int
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("入手ステージ Quest ID")]
    # [PropertyOrder(6)]
    QuestIdList: list[int]

# [Description("武具セット")]
# [MessagePackObject(True)]
@dataclass
class EquipmentSetMB(MasterBookBase):
    # [Description("セット効果リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    EffectList: list[EquipmentSetEffect]
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str

# [Description("APIエラーコード")]
# [MessagePackObject(True)]
@dataclass
class ErrorCodeMB(MasterBookBase):
    # [Description("メッセージタイプ")]
    # [PropertyOrder(1)]
    ErrorMessageType: ErrorMessageType

# [Description("よくある質問リスト")]
# [MessagePackObject(True)]
@dataclass
class FaqListMB(MasterBookBase):
    # [Description("質問項目タイトルKey")]
    # [PropertyOrder(1)]
    QuestionTitleKey: str
    # [Description("遷移先URL")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    TransferUrl: TranslatedText

# [Description("フレンドキャンペーン")]
# [MessagePackObject(True)]
@dataclass
class FriendCampaignMB(MasterBookBase, IHasStartEndTime, ICharacterImage):
    # [Description("キャラ画像Id")]
    # [PropertyOrder(4)]
    CharacterImageId: int
    # [Description("キャラ画像サイズ")]
    # [PropertyOrder(7)]
    CharacterImageSize: float
    # [Description("キャラ画像座標X")]
    # [PropertyOrder(5)]
    CharacterImageX: float
    # [Description("キャラ画像座標Y")]
    # [PropertyOrder(6)]
    CharacterImageY: float
    # [Description("コード入力有効期間")]
    # [PropertyOrder(3)]
    CodeExpirationPeriod: int
    # [Description("招待コード入力上限数")]
    # [PropertyOrder(10)]
    CodeLimitCount: int
    # [Description("終了時刻")]
    # [PropertyOrder(2)]
    EndTime: str
    # [Description("対象フレンドミッションリスト")]
    # [PropertyOrder(8)]
    FriendMissionIdList: list[int]
    # [Description("招待コード入力報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(11)]
    RewardItemList: list[UserItem]
    # [Description("開始時刻")]
    # [PropertyOrder(1)]
    StartTime: str
    # [Description("キャンペーンタイトル")]
    # [PropertyOrder(9)]
    Title: str

# [Description("フレンドミッション")]
# [MessagePackObject(True)]
@dataclass
class FriendMissionMB(MasterBookBase, IHasStartEndTime):
    # [Description("ミッションタイプ")]
    # [PropertyOrder(3)]
    AchievementType: MissionAchievementType
    # [Description("終了時刻")]
    # [PropertyOrder(6)]
    EndTime: str
    # [Description("ミッション名")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("達成要求値")]
    # [PropertyOrder(4)]
    RequireValue: int
    # [Description("報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(8)]
    RewardList: list[UserItem]
    # [Description("表示優先度")]
    # [PropertyOrder(7)]
    SortOrder: int
    # [Description("開始時刻")]
    # [PropertyOrder(5)]
    StartTime: str
    # [Description("遷移先")]
    # [PropertyOrder(2)]
    TransitionDestination: MissionTransitionDestinationType

# [Description("ガチャ筐体")]
# [MessagePackObject(True)]
@dataclass
class GachaCaseMB(MasterBookBase, IHasJstStartEndTime):
    # [Description("表示順(降順)")]
    # [PropertyOrder(3)]
    DisplayOrder: int
    # [Description("属性(属性ガチャ用)")]
    # [PropertyOrder(5)]
    ElementType: ElementType
    # [Description("新ガチャの終了時間(JST)")]
    # [PropertyOrder(12)]
    EndTimeFixJST: str
    # [Description("ガチャ天井表示用フラグ")]
    # [PropertyOrder(10)]
    GachaCaseFlags: Flags[GachaCaseFlags]
    # [Description("GachaCaseUiMBのID")]
    # [PropertyOrder(1)]
    GachaCaseUiId: int
    # [Description("カテゴリー")]
    # [PropertyOrder(2)]
    GachaCategoryType: GachaCategoryType
    # [Description("運命(運命ガチャ用)")]
    # [PropertyOrder(7)]
    GachaDestinyType: GachaDestinyType
    # [Description("ガチャグループタイプ")]
    # [PropertyOrder(4)]
    GachaGroupType: GachaGroupType
    # [Description("ガチャの日数制限(プレイヤー生成時から計算、０は無視)")]
    # [PropertyOrder(13)]
    GachaLimitDayFromCreatePlayer: int
    # [Description("聖遺物(聖天使の信託ガチャ用)")]
    # [PropertyOrder(6)]
    GachaRelicType: GachaRelicType
    # [Description("表示用残り時間初期化タイプ")]
    # [PropertyOrder(9)]
    GachaResetType: GachaResetType
    # [Description("セレクトリストタイプ")]
    # [PropertyOrder(8)]
    GachaSelectListType: GachaSelectListType
    # [Description("新ガチャの開始時間(JST)")]
    # [PropertyOrder(11)]
    StartTimeFixJST: str

# [Description("ガチャ筐体描画用")]
# [MessagePackObject(True)]
@dataclass
class GachaCaseUiMB(MasterBookBase):
    # [Description("追加報酬アイテム")]
    # [Nest(False, 0)]
    # [PropertyOrder(20)]
    AddRewardItems: list[UserItem]
    # [Description("バナー画像番号")]
    # [PropertyOrder(13)]
    BannerImageNumber: int
    # [Description("バナー")]
    # [PropertyOrder(1)]
    BannerKey: str
    # [Description("天井テキスト")]
    # [PropertyOrder(21)]
    CeilingCountFormatKey: str
    # [Description("レイアウト")]
    # [Nest(False, 0)]
    # [PropertyOrder(12)]
    CustomTextLayout: CustomTextLayout
    # [Description("詳細ダイアログ 詳細")]
    # [PropertyOrder(18)]
    DetailDialogDetailKey: str
    # [Description("詳細ダイアログ 見出し")]
    # [PropertyOrder(17)]
    DetailDialogHeadingKey: str
    # [Description("詳細ダイアログ 注意")]
    # [PropertyOrder(19)]
    DetailDialogNotesKey: str
    # [Description("武具図鑑タブ番号")]
    # [PropertyOrder(15)]
    EquipmentPictureBookTabIndex: int
    # [Description("説明補足")]
    # [PropertyOrder(3)]
    ExplanationKey: str
    # [Description("ボーナスゲージタイプ")]
    # [PropertyOrder(16)]
    GachaBonusGaugeType: GachaBonusGaugeType
    # [Description("ボタンメッセージキー")]
    # [PropertyOrder(7)]
    GachaButtonMessageKey: str
    # [Description("ヘッダーアイテム1")]
    # [Nest(False, 0)]
    # [PropertyOrder(8)]
    HeaderItem1: UserItem
    # [Description("ヘッダーアイテム2")]
    # [Nest(False, 0)]
    # [PropertyOrder(9)]
    HeaderItem2: UserItem
    # [Description("ヘッダーアイテム3")]
    # [Nest(False, 0)]
    # [PropertyOrder(10)]
    HeaderItem3: UserItem
    # [Description("回数報酬表示")]
    # [PropertyOrder(11)]
    IsLotteryViewShowBonusItem: bool
    # [Description("タイトル")]
    # [PropertyOrder(2)]
    NameKey: str
    # [Description("ピックアップされるキャラクター")]
    # [PropertyOrder(4)]
    PickUpCharacterId: int
    # [Description("時間テキスト")]
    # [PropertyOrder(14)]
    TimeFormatKey: str
    # [Description("タイトル色")]
    # [PropertyOrder(5)]
    TitleColorType: GachaTitleColorType

# [Description("運命ガチャ追加キャラクター")]
# [MessagePackObject(True)]
@dataclass
class GachaDestinyAddCharacterMB(MasterBookBase):
    # [Description("キャラクターID")]
    # [PropertyOrder(1)]
    CharacterId: int
    # [Description("終了時間参照用GachaSelectListMBのID")]
    # [PropertyOrder(4)]
    EndGachaSelectListId: int
    # [Description("セレクトリスト追加タイプ")]
    # [PropertyOrder(2)]
    GachaAddCharacterType: GachaAddCharacterType
    # [Description("開始時間参照用GachaSelectListMBのID")]
    # [PropertyOrder(3)]
    StartGachaSelectListId: int

# [Description("ガチャセレクトリスト")]
# [MessagePackObject(True)]
@dataclass
class GachaSelectListMB(MasterBookBase, IHasJstStartEndTime):
    # [Description("設定可能キャラクターIDリスト")]
    # [PropertyOrder(5)]
    CharacterIdList: list[int]
    # [Description("終了時間(JST)")]
    # [PropertyOrder(3)]
    EndTimeFixJST: str
    # [Description("ガチャセレクトリストタイプ")]
    # [PropertyOrder(1)]
    GachaSelectListType: GachaSelectListType
    # [Description("新規キャラクターIDリスト")]
    # [PropertyOrder(6)]
    NewCharacterIdList: list[int]
    # [Description("優先度")]
    # [PropertyOrder(4)]
    OrderNumber: int
    # [Description("開始時間(JST)")]
    # [PropertyOrder(2)]
    StartTimeFixJST: str

# [Description("グランドバトル城")]
# [MessagePackObject(True)]
@dataclass
class GlobalGvgCastleMB(MasterBookBase):
    # [Description("隣接する城のIDリスト")]
    # [PropertyOrder(4)]
    AdjacentCastleIds: list[int]
    # [Description("拠点ポイント")]
    # [PropertyOrder(3)]
    CastlePoint: int
    # [Description("城タイプ")]
    # [PropertyOrder(2)]
    CastleType: CastleType
    # [Description("拠点報酬_固定")]
    # [Nest(True, 0)]
    # [PropertyOrder(6)]
    GlobalGvgFixedRewards: GlobalGvgFixedRewards
    # [Description("抽選報酬ID")]
    # [PropertyOrder(7)]
    LotteryRewardId: int
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("初期城グループ")]
    # [PropertyOrder(5)]
    Priority: int

# [Description("ギルドレベル")]
# [MessagePackObject(True)]
@dataclass
class GuildLevelMB(MasterBookBase):
    # [Description("1日の経験値獲得上限")]
    # [PropertyOrder(4)]
    DayLimitExp: int
    # [Description("レベル")]
    # [PropertyOrder(1)]
    Level: int
    # [Description("加入可能人数")]
    # [PropertyOrder(2)]
    NumberOfPossibleJoinPeople: int
    # [Description("必要累計経験値")]
    # [PropertyOrder(3)]
    RequiredTotalExp: int

# [Description(" ギルドレイドボスデータ")]
# [MessagePackObject(True)]
@dataclass
class GuildRaidBossMB(MasterBookBase, IHasStartEndTime):
    # [Description("アクティブスキルIDのリスト")]
    # [PropertyOrder(17)]
    ActiveSkillIds: list[int]
    # [Description("バナーテキスト")]
    # [PropertyOrder(23)]
    BannerText: str
    # [Description("ベースパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(14)]
    BaseParameter: BaseParameter
    # [Description("バトルパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(15)]
    BattleParameter: BattleParameter
    # [Description("戦闘力")]
    # [PropertyOrder(12)]
    BattlePower: int
    # [Description("キャラクター座標X")]
    # [PropertyOrder(21)]
    CharacterImageX: float
    # [Description("キャラクター座標Y")]
    # [PropertyOrder(22)]
    CharacterImageY: float
    # [Description("レアリティ")]
    # [PropertyOrder(13)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("属性")]
    # [PropertyOrder(10)]
    ElementType: ElementType
    # [Description("終了日時（現地時間")]
    # [PropertyOrder(5)]
    EndTime: str
    # [Description("敵のランク")]
    # [PropertyOrder(8)]
    EnemyRank: int
    # [Description("ギルドダメージバー")]
    # [Nest(False, 0)]
    # [PropertyOrder(20)]
    GuildDamageBar: list[GuildRaidDamageBar]
    # [Description("ボス種別")]
    # [PropertyOrder(3)]
    GuildRaidBossType: GuildRaidBossType
    # [Description("ギルドレイドボタン座標U")]
    # [PropertyOrder(24)]
    GuildRaidButtonU: float
    # [Description("ギルドレイドボタン座標V")]
    # [PropertyOrder(25)]
    GuildRaidButtonV: float
    # [Description("職業")]
    # [PropertyOrder(11)]
    JobFlags: Flags[JobFlags]
    # [Description("名称キー")]
    # [PropertyOrder(9)]
    NameKey: str
    # [Description("通常ダメージバー")]
    # [Nest(False, 0)]
    # [PropertyOrder(19)]
    NormalDamageBar: list[GuildRaidDamageBar]
    # [Description("通常攻撃として使ってくるスキルID")]
    # [PropertyOrder(16)]
    NormalSkillId: int
    # [Description("パッシブスキルIDのリスト")]
    # [PropertyOrder(18)]
    PassiveSkillIds: list[int]
    # [Description("必要ギルド貢献値")]
    # [PropertyOrder(6)]
    ReleasableGuildFame: int
    # [Description("開始日時（現地時間）")]
    # [PropertyOrder(4)]
    StartTime: str
    # [Description("ユニットアイコンID")]
    # [PropertyOrder(2)]
    UnitIconId: int
    # [Description("ユニットアイコンタイプ")]
    # [PropertyOrder(1)]
    UnitIconType: UnitIconType

# [Description(" ギルドレイド報酬データ")]
# [MessagePackObject(True)]
@dataclass
class GuildRaidRewardMB(MasterBookBase):
    # [Description("ギルドダメージバー報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    GuildDamageBarRewards: list[GuildDamageBarReward]
    # [Description("一回の挑戦で獲得できるギルド経験値")]
    # [PropertyOrder(2)]
    GuildExpPerChallenge: int
    # [Description("ギルドレイドボスID")]
    # [PropertyOrder(1)]
    GuildRaidBossId: int
    # [Description("非表示ワールドダメージ")]
    # [PropertyOrder(8)]
    HideWorldDamage: int
    # [Description("抽選報酬ID")]
    # [PropertyOrder(3)]
    LotteryRewardId: int
    # [Description("通常ダメージバー報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    NormalDamageBarRewards: list[NormalDamageBarReward]
    # [Description("武具Lvリスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    QuestClearEquipmentLvList: list[GuildRaidQuestClearEquipmentLvList]
    # [Description("ワールド報酬目標リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(7)]
    WorldDamageBarRewards: list[WorldDamageBarReward]

# [Description("GvG修練レベル")]
# [MessagePackObject(True)]
@dataclass
class GvGServerLvMB(MasterBookBase):
    # [Description("経過日数")]
    # [PropertyOrder(2)]
    ElapsedDays: int
    # [Description("修練レベル")]
    # [PropertyOrder(1)]
    Lv: int
    # [Description("グランドバトル神殿下位最小配置数")]
    # [PropertyOrder(12)]
    MinCharacterNumGrandBattleLargeBronze: int
    # [Description("グランドバトル神殿上位最小配置数")]
    # [PropertyOrder(6)]
    MinCharacterNumGrandBattleLargeGolden: int
    # [Description("グランドバトル神殿中位最小配置数")]
    # [PropertyOrder(9)]
    MinCharacterNumGrandBattleLargeSilver: int
    # [Description("グランドバトル教会下位最小配置数")]
    # [PropertyOrder(13)]
    MinCharacterNumGrandBattleMediumBronze: int
    # [Description("グランドバトル教会上位最小配置数")]
    # [PropertyOrder(7)]
    MinCharacterNumGrandBattleMediumGolden: int
    # [Description("グランドバトル教会中位最小配置数")]
    # [PropertyOrder(10)]
    MinCharacterNumGrandBattleMediumSilver: int
    # [Description("グランドバトル城下位最小配置数")]
    # [PropertyOrder(14)]
    MinCharacterNumGrandBattleSmallBronze: int
    # [Description("グランドバトル城上位最小配置数")]
    # [PropertyOrder(8)]
    MinCharacterNumGrandBattleSmallGolden: int
    # [Description("グランドバトル城中位最小配置数")]
    # [PropertyOrder(11)]
    MinCharacterNumGrandBattleSmallSilver: int
    # [Description("ギルドバトル神殿最小配置数")]
    # [PropertyOrder(3)]
    MinCharacterNumGuildBattleLarge: int
    # [Description("ギルドバトル教会最小配置数")]
    # [PropertyOrder(4)]
    MinCharacterNumGuildBattleMedium: int
    # [Description("ギルドバトル城最小配置数")]
    # [PropertyOrder(5)]
    MinCharacterNumGuildBattleSmall: int

# [Description("ヘルプ")]
# [MessagePackObject(True)]
@dataclass
class HelpMB(MasterBookBase):
    # [Description("ヘルプパートリスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    HelpPartInfoList: list[HelpPartInfo]
    # [Description("ヘルプタイトル")]
    # [PropertyOrder(1)]
    HelpTitle: str
    # [Description("表示フラグ")]
    # [PropertyOrder(4)]
    IsDisplayed: bool
    # [Description("チュートリアル説明ID")]
    # [PropertyOrder(3)]
    TutorialDescriptionId: int

# [Description("お問い合わせボタン")]
# [MessagePackObject(True)]
@dataclass
class InquiryButtonMB(MasterBookBase):
    # [Description("ボタンテキスト")]
    # [PropertyOrder(1)]
    ButtonTextKey: str
    # [Description("ボタンタイプ")]
    # [PropertyOrder(2)]
    ButtonType: InquiryButtonType
    # [Description("メール本文キー")]
    # [PropertyOrder(4)]
    MailBodyKey: str
    # [Description("メール件名キー")]
    # [PropertyOrder(3)]
    MailSubjectKey: str
    # [Description("タイムサーバーID")]
    # [PropertyOrder(6)]
    TimeServerIds: list[int]
    # [Description("遷移先URL")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    TransferUrl: TranslatedText

# [Description("アイテムの表示情報")]
# [MessagePackObject(True)]
@dataclass
class ItemMB(MasterBookBase, IHasStartEndTime):
    # [Description("説明文キー")]
    # [PropertyOrder(5)]
    DescriptionKey: str
    # [Description("表示名キー")]
    # [PropertyOrder(4)]
    DisplayName: str
    # [Description("終了時刻")]
    # [PropertyOrder(9)]
    EndTime: str
    # [Description("アイコンId")]
    # [PropertyOrder(11)]
    IconId: int
    # [Description("アイテムID")]
    # [PropertyOrder(2)]
    ItemId: int
    # [Description("レアリティ")]
    # [PropertyOrder(6)]
    ItemRarityFlags: Flags[ItemRarityFlags]
    # [Description("アイテム種別")]
    # [PropertyOrder(1)]
    ItemType: ItemType
    # [Description("所持数上限")]
    # [PropertyOrder(10)]
    MaxItemCount: int
    # [Description("名称キー")]
    # [PropertyOrder(3)]
    NameKey: str
    # [Description("第2フレーム値")]
    # [PropertyOrder(14)]
    SecondaryFrameNum: int
    # [Description("第2フラーム種類")]
    # [PropertyOrder(13)]
    SecondaryFrameType: SecondaryFrameType
    # [Description("並び順（降順）")]
    # [PropertyOrder(7)]
    SortOrder: int
    # [Description("開始時刻")]
    # [PropertyOrder(8)]
    StartTime: str
    # [Description("遷移先ID")]
    # [PropertyOrder(12)]
    TransferSpotId: int

# [Description("レビュー誘導用データ")]
# [MessagePackObject(True)]
@dataclass
class LeadReviewMB(MasterBookBase):
    # [DateTimeString]
    # [Description("リセット日時")]
    # [PropertyOrder(1)]
    ResetDate: str

# [Description("レジェンドリーグ階級データ")]
# [MessagePackObject(True)]
@dataclass
class LegendLeagueClassMB(MasterBookBase):
    # [Description("階級名キー")]
    # [PropertyOrder(2)]
    ClassNameKey: str
    # [Description("レジェンドリーグ階級")]
    # [PropertyOrder(1)]
    ClassType: LegendLeagueClassType
    # [Description("最低必要ランク")]
    # [PropertyOrder(4)]
    RequiredMinimumRank: int
    # [Description("要求ポイント")]
    # [PropertyOrder(3)]
    RequiredPoint: int

# [Description("レベルリンク")]
# [MessagePackObject(True)]
@dataclass
class LevelLinkMB(MasterBookBase):
    # [Description("パーティーレベル")]
    PartyLevel: int
    # [Description("パーティーSubレベル")]
    PartySubLevel: int
    # [Description("レベルアップに必要なアイテム")]
    # [Nest(False, 0)]
    RequiredLevelUpItems: list[UserItem]

# [Description("期間限定イベント")]
# [MessagePackObject(True)]
@dataclass
class LimitedEventMB(MasterBookBase, IHasStartEndTime):
    # [Description("終了日時")]
    # [PropertyOrder(3)]
    EndTime: str
    # [Description("イベントの種類")]
    # [PropertyOrder(1)]
    LimitedEventType: LimitedEventType
    # [Description("開始日時")]
    # [PropertyOrder(2)]
    StartTime: str

# [Description("期間限定ログインボーナス")]
# [MessagePackObject(True)]
@dataclass
class LimitedLoginBonusMB(MasterBookBase, IHasStartEndTime):
    # [Description("訴求文言")]
    # [PropertyOrder(8)]
    AppealTextKey: str
    # [Description("キャラ画像Id")]
    # [PropertyOrder(4)]
    CharacterImageId: int
    # [Description("終了日時")]
    # [PropertyOrder(2)]
    EndTime: str
    # [Description("報酬背景画像ID")]
    # [PropertyOrder(5)]
    RewardBackgroundImageId: int
    # [Description("報酬リストID")]
    # [PropertyOrder(3)]
    RewardListId: int
    # [Description("特別報酬訴求文言")]
    # [PropertyOrder(9)]
    SpecialRewardAppealTextKey: str
    # [Description("特別報酬背景画像ID")]
    # [PropertyOrder(6)]
    SpecialRewardBackgroundImageId: int
    # [Description("特別報酬カウントテキスト色")]
    # [PropertyOrder(12)]
    SpecialRewardCountTextColor: str
    # [Description("特別報酬ラベル色")]
    # [PropertyOrder(10)]
    SpecialRewardLabelTextColor: str
    # [Description("特別報酬ラベルアウトライン色")]
    # [PropertyOrder(11)]
    SpecialRewardLabelTextOutlineColor: str
    # [Description("開始日時")]
    # [PropertyOrder(1)]
    StartTime: str
    # [Description("タイトル")]
    # [PropertyOrder(7)]
    TitleTextKey: str

# [Description("期間限定ログインボーナス報酬リスト")]
# [MessagePackObject(True)]
@dataclass
class LimitedLoginBonusRewardListMB(MasterBookBase):
    # [Description("日別報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(1)]
    DailyRewardList: list[DailyLimitedLoginBonusItem]
    # [Description("毎日報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    EveryDayRewardItem: EveryDayLimitedLoginBonusItem
    # [Description("毎日報酬有無")]
    # [PropertyOrder(2)]
    ExistEveryDayReward: bool
    # [Description("特別報酬有無")]
    # [PropertyOrder(4)]
    ExistSpecialReward: bool
    # [Description("特別報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    SpecialRewardItem: SpecialLimitedLoginBonusItem

# [Description("期間限定ミッション")]
# [MessagePackObject(True)]
@dataclass
class LimitedMissionMB(MasterBookBase, IHasStartEndTime):
    # [Description("訴求文言")]
    # [PropertyOrder(8)]
    AppealTextKey: str
    # [Description("キャラ画像Id")]
    # [PropertyOrder(3)]
    CharacterImageId: int
    # [Description("キャラ画像サイズ")]
    # [PropertyOrder(6)]
    CharacterImageSize: float
    # [Description("キャラ画像座標X")]
    # [PropertyOrder(4)]
    CharacterImageX: float
    # [Description("キャラ画像座標Y")]
    # [PropertyOrder(5)]
    CharacterImageY: float
    # [Description("終了日時")]
    # [PropertyOrder(2)]
    EndTime: str
    # [Description("開始日時")]
    # [PropertyOrder(1)]
    StartTime: str
    # [Description("対象ミッションID")]
    # [PropertyOrder(9)]
    TargetMissionIdList: list[int]
    # [Description("タイトル")]
    # [PropertyOrder(7)]
    TitleTextKey: str

# [Description("ギルドバトル城")]
# [MessagePackObject(True)]
@dataclass
class LocalGvgCastleMB(MasterBookBase):
    # [Description("隣接する城のIDリスト")]
    # [PropertyOrder(3)]
    AdjacentCastleIds: list[int]
    # [Description("城タイプ")]
    # [PropertyOrder(2)]
    CastleType: CastleType
    # [Description("拠点報酬_固定")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    LocalGvgFixedRewards: list[UserItem]
    # [Description("拠点確率報酬ID")]
    # [PropertyOrder(5)]
    LotteryRewardId: int
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str

# [Description("ローカル通知")]
# [MessagePackObject(True)]
@dataclass
class LocalPushNotificationMB(MasterBookBase, IHasStartEndTime):
    # [Description("終了時間")]
    # [PropertyOrder(4)]
    EndTime: str
    # [Description("グループID")]
    # [PropertyOrder(2)]
    GroupId: int
    # [Description("送信条件")]
    # [PropertyOrder(8)]
    LocalNotificationSendType: LocalNotificationSendType
    # [Description("通知タイプ")]
    # [PropertyOrder(1)]
    LocalNotificationType: LocalNotificationType
    # [Description("メッセージ")]
    # [PropertyOrder(7)]
    MessageKey: str
    # [Description("優先度")]
    # [PropertyOrder(5)]
    Priority: int
    # [Description("送信時刻")]
    # [PropertyOrder(9)]
    SendTime: str
    # [Description("開始時間")]
    # [PropertyOrder(3)]
    StartTime: str
    # [Description("タイトル")]
    # [PropertyOrder(6)]
    TitleKey: str

# [Description("幻影の神殿バナー")]
# [MessagePackObject(True)]
@dataclass
class LocalRaidBannerMB(MasterBookBase):
    # [Description("デコレーション色")]
    # [PropertyOrder(3)]
    DecorationColor: str
    # [Description("デコレーションID")]
    # [PropertyOrder(2)]
    DecorationId: int
    # [Description("クエスト名キー")]
    # [PropertyOrder(1)]
    NameKey: str

# [Description("幻影の神殿敵データ")]
# [MessagePackObject(True)]
@dataclass
class LocalRaidEnemyMB(MasterBookBase, IBattleEnemy):
    # [Description("アクティブスキルIDのリスト")]
    # [PropertyOrder(12)]
    ActiveSkillIds: list[int]
    # [Description("ベースパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(9)]
    BaseParameter: BaseParameter
    # [Description("敵キャラクターID")]
    # [PropertyOrder(14)]
    BattleEnemyCharacterId: int
    # [Description("バトルパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(10)]
    BattleParameter: BattleParameter
    # [Description("戦闘力")]
    # [PropertyOrder(5)]
    BattlePower: int
    # [Description("レアリティ")]
    # [PropertyOrder(8)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("属性")]
    # [PropertyOrder(7)]
    ElementType: ElementType
    # [Description("敵調整ID")]
    # [PropertyOrder(16)]
    EnemyAdjustId: int
    # [Description("敵武具ID")]
    # [PropertyOrder(15)]
    EnemyEquipmentId: int
    # [Description("敵のランク")]
    # [PropertyOrder(4)]
    EnemyRank: int
    # [Description("職業")]
    # [PropertyOrder(6)]
    JobFlags: Flags[JobFlags]
    # [Description("名称キー")]
    # [PropertyOrder(3)]
    NameKey: str
    # [Description("通常攻撃として使ってくるスキルID")]
    # [PropertyOrder(11)]
    NormalSkillId: int
    # [Description("パッシブスキルIDのリスト")]
    # [PropertyOrder(13)]
    PassiveSkillIds: list[int]
    # [Description("ユニットアイコンID")]
    # [PropertyOrder(2)]
    UnitIconId: int
    # [Description("ユニットアイコンタイプ")]
    # [PropertyOrder(1)]
    UnitIconType: UnitIconType

# [Description("幻影の神殿イベントクエストグループ")]
# [MessagePackObject(True)]
@dataclass
class LocalRaidEventQuestGroupMB(MasterBookBase):
    # [Description("イベント追加挑戦回数")]
    # [PropertyOrder(4)]
    EventBattleCount: int
    # [Description("修練レベル")]
    # [PropertyOrder(3)]
    LocalRaidLevel: int
    # [Description("LocalRaidQuestMBのIdリスト")]
    # [PropertyOrder(1)]
    LocalRaidQuestIds: list[int]
    # [Description("ワールド生成経過日数")]
    # [PropertyOrder(5)]
    OverDayFromCreateWorldTime: int
    # [Description("イベント経過日数")]
    # [PropertyOrder(2)]
    OverDayFromStartEventTime: int

# [Description("幻影の神殿イベントスケジュール")]
# [MessagePackObject(True)]
@dataclass
class LocalRaidEventScheduleMB(MasterBookBase, IHasStartEndTime):
    # [Description("終了日時")]
    # [PropertyOrder(6)]
    EndTime: str
    # [Description("LocalRaidEventQuestGroupMBのIdリスト")]
    # [PropertyOrder(1)]
    LocalRaidEventQuestGroupIds: list[int]
    # [Description("イベントチュートリアルダイアログのID")]
    # [PropertyOrder(7)]
    LocalRaidEventTutorialId: int
    # [Description("イベントタイプ")]
    # [PropertyOrder(2)]
    LocalRaidEventType: LocalRaidEventType
    # [Description("報酬増加時間リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    LocalRaidStartEndTimes: list[LocalRaidStartEndTime]
    # [Description("報酬増加倍率(100%=10000)")]
    # [PropertyOrder(4)]
    RewardBonusRate: int
    # [Description("開始日時")]
    # [PropertyOrder(5)]
    StartTime: str

# [Description("幻影の神殿クエストグループ")]
# [MessagePackObject(True)]
@dataclass
class LocalRaidQuestGroupMB(MasterBookBase):
    # [Description("修練レベル")]
    # [PropertyOrder(2)]
    LocalRaidLevel: int
    # [Description("幻影の神殿Idグループリスト")]
    # [Nest(True, 0)]
    # [PropertyOrder(1)]
    LocalRaidQuestIdGroups: list[LocalRaidQuestIdGroup]
    # [Description("最大挑戦回数")]
    # [PropertyOrder(3)]
    MaxBattleCount: int
    # [Description("ワールド生成経過日数")]
    # [PropertyOrder(4)]
    OverDayFromCreateWorldTime: int

# [Description("幻影の神殿クエスト")]
# [MessagePackObject(True)]
@dataclass
class LocalRaidQuestMB(MasterBookBase):
    # [Description("初回報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    FirstBattleRewards: list[UserItem]
    # [Description("通常報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    FixedBattleRewards: list[UserItem]
    # [Description("レベル")]
    # [PropertyOrder(2)]
    Level: int
    # [Description("クエスト名キー")]
    # [PropertyOrder(1)]
    LocalRaidBannerId: int
    # [Description("敵Idリスト")]
    # [PropertyOrder(6)]
    LocalRaidEnemyIds: list[int]
    # [Description("個人戦力目安")]
    # [PropertyOrder(3)]
    RecommendedBattlePower: int

# [Description("ミッションクリア個数報酬")]
# [MessagePackObject(True)]
@dataclass
class MissionClearCountRewardMB(MasterBookBase):
    # [Description("ミッション種別")]
    # [PropertyOrder(1)]
    MissionGroupType: MissionGroupType
    # [Description("必要クリア数")]
    # [PropertyOrder(2)]
    RequiredClearCount: int
    # [Description("報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    RewardList: list[MissionReward]

# [Description("ミッションガイド")]
# [MessagePackObject(True)]
@dataclass
class MissionGuideMB(MasterBookBase, IHasStartEndTime):
    # [Description("ユーザ登録終了日時")]
    # [PropertyOrder(4)]
    EndTime: str
    # [Description("ガイドID")]
    # [PropertyOrder(1)]
    GuideId: int
    # [Description("ミッションId")]
    # [PropertyOrder(2)]
    MissionId: int
    # [Description("ガイド表示優先度A")]
    # [PropertyOrder(5)]
    SortOrderA: int
    # [Description("ガイド表示優先度B")]
    # [PropertyOrder(6)]
    SortOrderB: int
    # [Description("ユーザ登録開始日時")]
    # [PropertyOrder(3)]
    StartTime: str

# [Description("ミッション")]
# [MessagePackObject(True)]
@dataclass
class MissionMB(MasterBookBase, IHasStartEndTime):
    # [Description("ミッションタイプ")]
    # [PropertyOrder(6)]
    AchievementType: MissionAchievementType
    # [Description("ミッション説明")]
    # [PropertyOrder(4)]
    DescriptionKey: str
    # [Description("終了時刻")]
    # [PropertyOrder(9)]
    EndTime: str
    # [Description("ミッション種別")]
    # [PropertyOrder(1)]
    MissionType: MissionType
    # [Description("ミッション名")]
    # [PropertyOrder(3)]
    NameKey: str
    # [Description("開放日数")]
    # [PropertyOrder(2)]
    OpeningPeriod: int
    # [Description("達成要求値")]
    # [PropertyOrder(7)]
    RequireValue: int
    # [Description("報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(12)]
    RewardList: list[MissionReward]
    # [Description("表示優先度A")]
    # [PropertyOrder(10)]
    SortOrderA: int
    # [Description("表示優先度B")]
    # [PropertyOrder(11)]
    SortOrderB: int
    # [Description("開始時刻")]
    # [PropertyOrder(8)]
    StartTime: str
    # [Description("遷移先")]
    # [PropertyOrder(5)]
    TransitionDestination: MissionTransitionDestinationType

# [Description("ミッション機能解放")]
# [MessagePackObject(True)]
@dataclass
class MissionOpenContentMB(MasterBookBase):
    # [Description("ミッションタイプ")]
    # [PropertyOrder(1)]
    AchievementType: MissionAchievementType
    # [Description("機能解放")]
    # [PropertyOrder(2)]
    OpenCommandType: OpenCommandType

# [Description("ミッションタブ名")]
# [MessagePackObject(True)]
@dataclass
class MissionTabNameMB(MasterBookBase):
    # [Description("ミッション種別")]
    # [PropertyOrder(1)]
    MissionType: MissionType
    # [Description("ミッションタブ名")]
    # [PropertyOrder(2)]
    TabNameKey: str

# [Description("月間ログインボーナス")]
# [MessagePackObject(True)]
@dataclass
class MonthlyLoginBonusMB(MasterBookBase):
    # [Description("画像Id")]
    # [PropertyOrder(3)]
    ImageId: int
    # [Description("報酬リストID")]
    # [PropertyOrder(2)]
    RewardListId: int
    # [Description("年月")]
    # [PropertyOrder(1)]
    YearMonth: str

# [Description("月間ログインボーナス報酬リスト")]
# [MessagePackObject(True)]
@dataclass
class MonthlyLoginBonusRewardListMB(MasterBookBase):
    # [Description("日別ログイン報酬リスト")]
    # [Nest(True, 1)]
    # [PropertyOrder(1)]
    DailyRewardList: list[LoginDailyRewardInfo]
    # [Description("合計ログイン報酬リスト")]
    # [Nest(True, 1)]
    # [PropertyOrder(2)]
    LoginCountRewardList: list[LoginCountRewardInfo]

# [Description("新キャラミッション")]
# [MessagePackObject(True)]
@dataclass
class NewCharacterMissionMB(MasterBookBase, IHasJstStartEndTime):
    # [Description("キャラ画像Id")]
    # [PropertyOrder(4)]
    CharacterImageId: int
    # [Description("キャラ画像サイズ")]
    # [PropertyOrder(7)]
    CharacterImageSize: float
    # [Description("キャラ画像座標X")]
    # [PropertyOrder(5)]
    CharacterImageX: float
    # [Description("キャラ画像座標Y")]
    # [PropertyOrder(6)]
    CharacterImageY: float
    # [Description("終了日時")]
    # [PropertyOrder(2)]
    EndTimeFixJST: str
    # [DateTimeString]
    # [Description("強制開始時間")]
    # [PropertyOrder(3)]
    ForceStartTime: str
    # [Description("開始日時")]
    # [PropertyOrder(1)]
    StartTimeFixJST: str
    # [Description("対象ミッションID")]
    # [PropertyOrder(9)]
    TargetMissionIdList: list[int]
    # [Description("タイトル")]
    # [PropertyOrder(8)]
    TitleTextKey: str
    # [Description("Twitter")]
    # [PropertyOrder(11)]
    TwitterUrl: str
    # [Description("YouTube")]
    # [PropertyOrder(10)]
    YouTubeUrl: str

# [Description("コンテンツ開放")]
# [MessagePackObject(True)]
@dataclass
class OpenContentMB(MasterBookBase):
    # [Description("演出パス")]
    # [PropertyOrder(4)]
    AssetPath: str
    # [Description("開放内容キー")]
    # [PropertyOrder(3)]
    DescriptionKey: str
    # [Description("ガイド説明文")]
    # [PropertyOrder(8)]
    GuideDescriptionKey: str
    # [Description("ガイド表示優先順")]
    # [PropertyOrder(7)]
    GuideOrderNumber: int
    # [Description("ガイド表示タイプ")]
    # [PropertyOrder(6)]
    IsActiveGuide: bool
    # [Description("解放されるコマンドの種類")]
    # [PropertyOrder(5)]
    OpenCommandType: OpenCommandType
    # [Description("コンテンツ開放タイプ")]
    # [PropertyOrder(1)]
    OpenContentType: OpenContentType
    # [Description("コンテンツ開放値")]
    # [PropertyOrder(2)]
    OpenContentValue: int
    # [Description("トースト")]
    # [PropertyOrder(9)]
    ToastKey: str
    # [Description("トチュートリアルID")]
    # [PropertyOrder(10)]
    TutorialId: int

# [Description("パッシブスキル")]
# [MessagePackObject(True)]
@dataclass
class PassiveSkillMB(MasterBookBase):
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("サブセットスキルリスト")]
    # [Nest(True, 1)]
    # [PropertyOrder(2)]
    PassiveSkillInfos: list[PassiveSkillInfo]

# [Description("プレイヤーランク")]
# [MessagePackObject(True)]
@dataclass
class PlayerRankMB(MasterBookBase):
    # [Description("キャラパラメータ攻撃力ボーナス")]
    # [PropertyOrder(4)]
    AttackPowerBonus: int
    # [Description("キャラパラメータクリティカルボーナス")]
    # [PropertyOrder(9)]
    CriticalBonus: int
    # [Description("キャラパラメータクリダメ強化ボーナス")]
    # [PropertyOrder(13)]
    CriticalDamageEnhanceBonus: int
    # [Description("キャラパラメータ物魔防御貫通ボーナス")]
    # [PropertyOrder(8)]
    DamageEnhanceBonus: int
    # [Description("キャラパラメータカウンタボーナス")]
    # [PropertyOrder(14)]
    DamageReflectBonus: int
    # [Description("キャラパラメータ弱体効果命中ボーナス")]
    # [PropertyOrder(11)]
    DebuffHitBonus: int
    # [Description("キャラパラメータ防御貫通ボーナス")]
    # [PropertyOrder(7)]
    DefensePenetrationBonus: int
    # [Description("キャラパラメータ命中ボーナス")]
    # [PropertyOrder(10)]
    HitBonus: int
    # [Description("命中率ボーナス(パラメータX)")]
    # [PropertyOrder(16)]
    HitDirectPercentBonus: int
    # [Description("キャラパラメータHPボーナス")]
    # [PropertyOrder(5)]
    HpBonus: int
    # [Description("キャラパラメータHPドレインボーナス")]
    # [PropertyOrder(15)]
    HpDrainBonus: int
    # [Description("キャラパラメータHP%ボーナス")]
    # [PropertyOrder(6)]
    HpPercentBonus: int
    # [Description("レベルリンク枠最大数")]
    # [PropertyOrder(17)]
    LevelLinkMemberMaxCount: int
    # [Description("ランク")]
    # [PropertyOrder(1)]
    Rank: int
    # [Description("必要累計経験値")]
    # [PropertyOrder(2)]
    RequiredTotalExp: int
    # [Description("キャラパラメータスピードボーナス")]
    # [PropertyOrder(12)]
    SpeedBonus: int
    # [DateTimeString]
    # [Description("解放時間")]
    # [PropertyOrder(3)]
    StartTimeFixJST: str

# [Description("PVPランキング報酬")]
# [MessagePackObject(True)]
@dataclass
class PvpRankingRewardMB(MasterBookBase):
    # [Description("下限")]
    # [PropertyOrder(2)]
    LowerLimitRanking: int
    # [Description("PVPランキング報酬タイプ")]
    # [PropertyOrder(1)]
    PvpRankingRewardType: PvpRankingRewardType
    # [Description("報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    RewardList: list[UserItem]
    # [Description("上限")]
    # [PropertyOrder(3)]
    UpperLimitRanking: int

# [Description("放置バトルマップオブジェクト")]
# [MessagePackObject(True)]
@dataclass
class QuestMapBuildingMB(MasterBookBase):
    # [Description("デフォルトタイプID")]
    # [PropertyOrder(1)]
    DefaultTypeId: int
    # [Description("選択タイプID 1")]
    # [PropertyOrder(2)]
    SelectTypeId1: int
    # [Description("選択タイプID 2")]
    # [PropertyOrder(3)]
    SelectTypeId2: int
    # [Description("選択タイプID 3")]
    # [PropertyOrder(4)]
    SelectTypeId3: int

# [Description("クエスト")]
# [MessagePackObject(True)]
@dataclass
class QuestMB(MasterBookBase):
    # [Description("ベース戦闘力")]
    # [PropertyOrder(7)]
    BaseBattlePower: int
    # [Description("章ID")]
    # [MasterBookId(typeof)]
    # [PropertyOrder(1)]
    ChapterId: int
    # [Description("ゴールド(/m)")]
    # [PropertyOrder(3)]
    GoldPerMinute: int
    # [Description("最低獲得経験珠")]
    # [PropertyOrder(8)]
    MinCharacterExp: int
    # [Description("最低獲得プレイヤー経験値")]
    # [PropertyOrder(9)]
    MinPlayerExp: int
    # [Description("人口")]
    # [PropertyOrder(2)]
    Population: int
    # [Description("潜在宝珠(/d)")]
    # [PropertyOrder(4)]
    PotentialJewelPerDay: int
    # [Description("クエスト難易度")]
    # [PropertyOrder(6)]
    QuestDifficultyType: QuestDifficultyType
    # [Description("マップ建物ID")]
    # [PropertyOrder(5)]
    QuestMapBuildingId: int

# [Description("必要仮想通貨")]
# [MessagePackObject(True)]
@dataclass
class RequiredCurrencyMB(MasterBookBase):
    # [Description("ボス挑戦回数の購入に必要な仮想通貨")]
    # [PropertyOrder(3)]
    BossBattle: int
    # [Description("回数")]
    # [PropertyOrder(1)]
    Count: int
    # [Description("レジェンドリーグ挑戦回数に必要な仮想通貨")]
    # [PropertyOrder(5)]
    LegendLeague: int
    # [Description("レベルリンク枠開放に必要な仮想通貨")]
    # [PropertyOrder(7)]
    LevelLinkMember: int
    # [Description("PvP挑戦回数に必要な仮想通貨")]
    # [PropertyOrder(4)]
    Pvp: int
    # [Description("高速周回に必要な仮想通貨")]
    # [PropertyOrder(2)]
    Quick: int
    # [Description("訓練所挑戦回数の購入に必要な仮想通貨")]
    # [PropertyOrder(6)]
    TowerBattle: int

# [Description("スフィア")]
# [MessagePackObject(True)]
@dataclass
class SphereMB(MasterBookBase):
    # [Description("潜在能力変動情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(7)]
    BaseParameterChangeInfo: BaseParameterChangeInfo
    # [Description("バトルパラメータ変動情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(8)]
    BattleParameterChangeInfo: BattleParameterChangeInfo
    # [Description("スフィアの種類ID")]
    # [PropertyOrder(2)]
    CategoryId: int
    # [Description("説明文キー")]
    # [PropertyOrder(10)]
    DescriptionKey: str
    # [Description("攻撃系のスフィアか")]
    # [PropertyOrder(6)]
    IsAttackType: bool
    # [Description("スフィア強化に必要なアイテム")]
    # [Nest(False, 0)]
    # [PropertyOrder(9)]
    ItemListRequiredToCombine: list[UserItem]
    # [Description("スフィアレベル")]
    # [PropertyOrder(4)]
    Lv: int
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("レアリティ")]
    # [PropertyOrder(5)]
    RarityFlags: Flags[ItemRarityFlags]
    # [Description("タイプId")]
    # [PropertyOrder(3)]
    SphereType: SphereType

# [Description("国ボーナス")]
# [MessagePackObject(True)]
@dataclass
class StateBonusMB(MasterBookBase):
    # [Description("時空の洞窟時空コインボーナス")]
    # [PropertyOrder(5)]
    DungeonCoinBonusPercent: int
    # [Description("ギルドバトルギルドコインボーナス")]
    # [PropertyOrder(6)]
    GuildCoinBonusPercent: int
    # [Description("曜日ボーナスが有効か")]
    # [PropertyOrder(4)]
    IsActiveWeeklyBonus: bool
    # [Description("国ボーナス表示アイテムアイコン情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    ItemIconInfo: ItemIconInfo
    # [Description("国ボーナス表示テキスト")]
    # [PropertyOrder(1)]
    StateBonusNameTextKey: str
    # [Description("国ボーナス表示数値")]
    # [PropertyOrder(3)]
    StateBonusNumberTextKey: str
    # [Description("累計貢献メダル報酬ボーナス情報")]
    # [Nest(True, 0)]
    # [PropertyOrder(7)]
    TotalActivityMedalRewardBonusList: list[TotalActivityMedalRewardBonus]

# [Description("国")]
# [MessagePackObject(True)]
@dataclass
class StateMB(MasterBookBase):
    # [Description("クリファテキストキー")]
    # [PropertyOrder(5)]
    AppearQliphaId: int
    # [Description("クリファテキストキー")]
    # [PropertyOrder(4)]
    AppearQliphaKey: str
    # [Description("開始時間(JP)")]
    # [PropertyOrder(7)]
    BgmStartTimeJP: float
    # [Description("開始時間(US)")]
    # [PropertyOrder(8)]
    BgmStartTimeUS: float
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("国ボーナスID")]
    # [PropertyOrder(6)]
    StateBonusId: int
    # [Description("サブ名称キー")]
    # [PropertyOrder(2)]
    SubNameKey: str
    # [Description("テキストキー")]
    # [PropertyOrder(3)]
    TextKey: str

# [Description("Steam商品価格表")]
# [MessagePackObject(True)]
@dataclass
class SteamProductPriceListMB(MasterBookBase):
    # [Description("JPYでの価格")]
    # [PropertyOrder(1)]
    JpyProductPrice: int
    # [Description("価格表")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    ProductPriceInfoList: list[SteamProductPriceInfo]

# [Description("利用規約")]
# [MessagePackObject(True)]
@dataclass
class TermsMB(MasterBookBase):
    # [Description("DMM用か？")]
    # [PropertyOrder(2)]
    IsDmm: bool
    # [Description("プライバシーポリシー")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    PrivacyPolicy: TermsButtonInfo
    # [Description("サブスク規約")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    Subscription: TermsButtonInfo
    # [Description("利用規約")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    Terms: TermsButtonInfo
    # [Description("その他")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    TermsButtonInfos: list[TermsButtonInfo]
    # [Description("TimeServerMBのID")]
    # [PropertyOrder(1)]
    TimeServerId: int

# [Description("テキスト言語")]
# [MessagePackObject(True)]
@dataclass
class TextLanguageMB(MasterBookBase):
    # [Description("行末禁則文字")]
    # [PropertyOrder(3)]
    HyphenationBack: str
    # [Description("行頭禁則文字")]
    # [PropertyOrder(2)]
    HyphenationFront: str
    # [Description("分離禁止文字")]
    # [PropertyOrder(4)]
    HyphenationSeparable: list[str]
    # [Description("言語")]
    # [PropertyOrder(1)]
    LanguageType: LanguageType

# [Description("リソース")]
# [MessagePackObject(True)]
@dataclass
class TextResourceMB(MasterBookBase):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("英語")]
    # [PropertyOrder(2)]
    enUS: str
    # [Description("日本語")]
    # [PropertyOrder(3)]
    jaJP: str
    # [Description("韓国語")]
    # [PropertyOrder(4)]
    koKR: str
    # [Description("中国語(繁体字)")]
    # [PropertyOrder(6)]
    zhTW: str

# [Description("日本語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceJaJpMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("英語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceEnUsMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("韓国語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceKoKrMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("中国語(繁体字)")]
# [MessagePackObject(True)]
@dataclass
class TextResourceZhTwMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("中国語(簡体字)")]
# [MessagePackObject(True)]
@dataclass
class TextResourceZhCnMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("フランス語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceFrFrMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("スペイン語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceEsMxMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("ポルトガル語")]
# [MessagePackObject(True)]
@dataclass
class TextResourcePtBrMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("タイ語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceThThMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("インドネシア語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceIdIdMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("ベトナム語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceViVnMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("ロシア語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceRuRuMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("ドイツ語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceDeDeMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("アラビア語")]
# [MessagePackObject(True)]
@dataclass
class TextResourceArEgMB(MasterBookBase, ITextResource):
    # [Description("文字列キー")]
    # [PropertyOrder(1)]
    StringKey: str
    # [Description("")]
    # [PropertyOrder(2)]
    Text: str

# [Description("時差グループ")]
# [MessagePackObject(True)]
@dataclass
class TimeServerMB(MasterBookBase):
    # [Description("国コードリスト")]
    # [PropertyOrder(6)]
    CountryCodeList: list[str]
    # [Description("デフォルト設定言語")]
    # [PropertyOrder(3)]
    DefaultLanguageType: LanguageType
    # [Description("デフォルト設定ボイス言語")]
    # [PropertyOrder(4)]
    DefaultVoiceLanguageType: LanguageType
    # [Description("UTCとの時差(例 01:00:00)")]
    # [PropertyOrder(2)]
    DifferenceDateTimeFromUtc: str
    # [Description("表示名のキー")]
    # [PropertyOrder(5)]
    DisplayNameKey: str
    # [Description("時差グループ名")]
    # [PropertyOrder(1)]
    Name: str
    # [Description("時差グループタイプ")]
    # [PropertyOrder(2)]
    TimeServerType: TimeServerType

# [Description("Tips")]
# [MessagePackObject(True)]
@dataclass
class TipMB(MasterBookBase):
    # [Description("Tipメッセージキー")]
    # [PropertyOrder(1)]
    MessageKey: str
    # [Description("解放判定")]
    # [PropertyOrder(3)]
    OpenCommandType: OpenCommandType
    # [Description("遷移先")]
    # [PropertyOrder(2)]
    ViewTransitionType: ViewTransitionType

# [Description("累計貢献メダル報酬")]
# [MessagePackObject(True)]
@dataclass
class TotalActivityMedalRewardMB(MasterBookBase, IHasEventStartEndTime):
    # [Description("イベント終了時刻")]
    # [PropertyOrder(5)]
    EventEndTime: str
    # [Description("イベント報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    EventMissionRewardList: list[EventMissionReward]
    # [Description("イベント開始時刻")]
    # [PropertyOrder(4)]
    EventStartTime: str
    # [Description("ミッション種別")]
    # [PropertyOrder(1)]
    MissionGroupType: MissionGroupType
    # [Description("必要貢献メダル")]
    # [PropertyOrder(2)]
    RequiredActivityMedalCount: int
    # [Description("報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    RewardList: list[MissionReward]

# [Description("無窮の塔　敵データ")]
# [MessagePackObject(True)]
@dataclass
class TowerBattleEnemyMB(MasterBookBase, IBattleEnemy):
    # [Description("アクティブスキルIDのリスト")]
    # [PropertyOrder(15)]
    ActiveSkillIds: list[int]
    # [Description("ベースパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(5)]
    BaseParameter: BaseParameter
    # [Description("敵キャラクターID")]
    # [PropertyOrder(1)]
    BattleEnemyCharacterId: int
    # [Description("バトルパラメータ")]
    # [Nest(True, 1)]
    # [PropertyOrder(6)]
    BattleParameter: BattleParameter
    # [Description("戦闘力")]
    # [PropertyOrder(7)]
    BattlePower: int
    # [Description("レアリティ")]
    # [PropertyOrder(4)]
    CharacterRarityFlags: Flags[CharacterRarityFlags]
    # [Description("属性")]
    # [PropertyOrder(11)]
    ElementType: ElementType
    # [Description("敵調整値ID")]
    # [PropertyOrder(8)]
    EnemyAdjustId: int
    # [Description("敵武具ID")]
    # [PropertyOrder(2)]
    EnemyEquipmentId: int
    # [Description("敵のランク")]
    # [PropertyOrder(3)]
    EnemyRank: int
    # [Description("職業")]
    # [PropertyOrder(10)]
    JobFlags: Flags[JobFlags]
    # [Description("名称キー")]
    # [PropertyOrder(9)]
    NameKey: str
    # [Description("通常攻撃として使ってくるスキルID")]
    # [PropertyOrder(14)]
    NormalSkillId: int
    # [Description("パッシブスキルIDのリスト")]
    # [PropertyOrder(16)]
    PassiveSkillIds: list[int]
    # [Description("ユニットアイコンID")]
    # [PropertyOrder(13)]
    UnitIconId: int
    # [Description("ユニットアイコンタイプ")]
    # [PropertyOrder(12)]
    UnitIconType: UnitIconType

# [Description("無窮の塔　階層情報")]
# [MessagePackObject(True)]
@dataclass
class TowerBattleQuestMB(MasterBookBase):
    # [Description("クリアパーティの基準（ベース）戦闘力")]
    # [PropertyOrder(3)]
    BaseClearPartyDeckPower: int
    # [Description("確定獲得クリア報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    BattleRewardsConfirmed: list[UserItem]
    # [Description("初回獲得クリア報酬")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    BattleRewardsFirst: list[UserItem]
    # [Description("敵IDリスト")]
    # [PropertyOrder(4)]
    EnemyIds: list[int]
    # [Description("階層")]
    # [PropertyOrder(2)]
    Floor: int
    # [Description("抽選報酬情報")]
    # [PropertyOrder(7)]
    LotteryRewardInfoId: int
    # [Description("塔の種類")]
    # [PropertyOrder(1)]
    TowerType: TowerType

# [Description("交換所スフィア")]
# [MessagePackObject(True)]
@dataclass
class TradeShopSphereMB(MasterBookBase):
    # [Description("消費アイテム1")]
    # [Nest(False, 0)]
    # [PropertyOrder(2)]
    ConsumeItem1: UserItem
    # [Description("消費アイテム2")]
    # [Nest(False, 0)]
    # [PropertyOrder(3)]
    ConsumeItem2: UserItem
    # [Description("スフィアのLv")]
    # [PropertyOrder(1)]
    SphereLevel: int

# [Description("交換所タブ")]
# [MessagePackObject(True)]
@dataclass
class TradeShopTabMB(MasterBookBase, IHasStartEndTime):
    # [Description("定期自動更新(タイプ４の更新時間)")]
    # [PropertyOrder(14)]
    AutoUpdateTimes: list[int]
    # [Description("定期自動更新タイプ")]
    # [PropertyOrder(13)]
    AutoUpdateType: TradeShopAutoUpdateType
    # [Description("消費アイテムリスト(表示用)")]
    # [Nest(False, 0)]
    # [PropertyOrder(17)]
    ConsumeItemInfos: list[ConsumeItemInfo]
    # [Description("レイアウト")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    CustomTextLayout: CustomTextLayout
    # [Description("デコレーション色")]
    # [PropertyOrder(5)]
    DecorationColor: str
    # [Description("デコレーションId")]
    # [PropertyOrder(3)]
    DecorationId: int
    # [Description("デコレーションスペシャルId")]
    # [PropertyOrder(4)]
    DecorationSpecialId: int
    # [Description("終了日時")]
    # [PropertyOrder(20)]
    EndTime: str
    # [Description("アイコンId")]
    # [PropertyOrder(2)]
    IconId: int
    # [Description("強制非表示フラグ")]
    # [PropertyOrder(9)]
    IsHide: bool
    # [Description("未解放時に非表示にするフラグ")]
    # [PropertyOrder(11)]
    IsHideNotOpen: bool
    # [Description("手動更新可能フラグ")]
    # [PropertyOrder(15)]
    IsManualUpdate: bool
    # [Description("手動更新に必要なダイヤ数")]
    # [PropertyOrder(16)]
    ManualUpdateCurrencyCount: int
    # [Description("コンテンツ実行タイプ")]
    # [PropertyOrder(18)]
    OpenCommandType: OpenCommandType
    # [Description("並び順")]
    # [PropertyOrder(8)]
    SortOrder: int
    # [Description("開始日時")]
    # [PropertyOrder(19)]
    StartTime: str
    # [Description("タブ名")]
    # [PropertyOrder(7)]
    TabNameKey: str
    # [Description("店舗景品数")]
    # [PropertyOrder(17)]
    TradeShopItemCount: int
    # [Description("交換所種類")]
    # [PropertyOrder(12)]
    TradeShopType: TradeShopType

# [Description("宝箱天井設定")]
# [MessagePackObject(True)]
@dataclass
class TreasureChestCeilingMB(MasterBookBase):
    # [Description("天井条件回数")]
    # [PropertyOrder(2)]
    CeilingCount: int
    # [Description("天井を適用するTreasureChestItemのId")]
    # [PropertyOrder(1)]
    TreasureChestItemId: int

# [Description("宝箱から得られるアイテム")]
# [MessagePackObject(True)]
@dataclass
class TreasureChestItemMB(MasterBookBase):
    # [Description("固定アイテムリスト")]
    # [Nest(True, 1)]
    # [PropertyOrder(4)]
    FixItemList: list[TreasureChestFixItem]
    # [Description("抽選報酬ID")]
    # [PropertyOrder(2)]
    LotteryRewardId: int
    # [Description("選択アイテムリスト")]
    # [Nest(True, 0)]
    # [PropertyOrder(3)]
    SelectItemList: list[TreasureChestSelectItem]
    # [Description("ItemListの参照先")]
    # [PropertyOrder(1)]
    TreasureChestItemListType: TreasureChestItemListType

# [Description("宝箱、宝石袋など")]
# [MessagePackObject(True)]
@dataclass
class TreasureChestMB(MasterBookBase, IHasStartEndTime):
    # [Description("開けるのに必要な鍵のID ※0の場合無効")]
    # [PropertyOrder(7)]
    ChestKeyItemId: int
    # [Description("説明文キー")]
    # [PropertyOrder(3)]
    DescriptionKey: str
    # [Description("表示名キー")]
    # [PropertyOrder(2)]
    DisplayNameKey: str
    # [Description("終了日時")]
    # [PropertyOrder(13)]
    EndTime: str
    # [Description("アイコンID")]
    # [PropertyOrder(4)]
    IconId: int
    # [Description("レアリティ")]
    # [PropertyOrder(5)]
    ItemRarityFlags: Flags[ItemRarityFlags]
    # [Description("所持数上限")]
    # [PropertyOrder(9)]
    MaxItemCount: int
    # [Description("必要個数")]
    # [PropertyOrder(8)]
    MinOpenCount: int
    # [Description("名称キー")]
    # [PropertyOrder(1)]
    NameKey: str
    # [Description("第2フレーム値")]
    # [PropertyOrder(11)]
    SecondaryFrameNum: int
    # [Description("第2フラーム種類")]
    # [PropertyOrder(10)]
    SecondaryFrameType: SecondaryFrameType
    # [Description("開始日時")]
    # [PropertyOrder(14)]
    StartTime: str
    # [Description("TreasureChestItemMBのIdリスト")]
    # [PropertyOrder(12)]
    TreasureChestItemIdList: list[int]
    # [Description("宝箱の報酬判定方法タイプ")]
    # [PropertyOrder(6)]
    TreasureChestLotteryType: TreasureChestLotteryType

# [Description("チュートリアル詳細")]
# [MessagePackObject(True)]
@dataclass
class TutorialDescriptionMB(MasterBookBase):
    # [Description("HelpMB ID(チュートリアル用)")]
    # [PropertyOrder(2)]
    HelpId: int
    # [Description("可変画像キャラID")]
    # [PropertyOrder(6)]
    ImageCharacterId: int
    # [Description("可変画像アイテム1")]
    # [Nest(False, 0)]
    # [PropertyOrder(4)]
    ImageItem1: UserItem
    # [Description("可変画像アイテム2")]
    # [Nest(False, 0)]
    # [PropertyOrder(5)]
    ImageItem2: UserItem
    # [Description("画像位置フォーマットタイプ")]
    # [PropertyOrder(3)]
    ImagePositionFormatType: ImagePositionFormatType
    # [Description("ページ情報")]
    # [Nest(False, 0)]
    # [PropertyOrder(1)]
    PageInfo: list[TutorialDescriptionPageInfo]

# [Description("チュートリアルテキストボックス")]
# [MessagePackObject(True)]
@dataclass
class TutorialTextBoxMB(MasterBookBase):
    # [Description("キャラアイコンのキャラID")]
    # [PropertyOrder(2)]
    CharacterId: int
    # [Description("テキストキー")]
    # [PropertyOrder(1)]
    TextKey: str
    # [Description("ボイスファイルパス")]
    # [PropertyOrder(3)]
    VoiceJPFilePath: str
    # [Description("ボイスファイルパス")]
    # [PropertyOrder(4)]
    VoiceUSFilePath: str

# [Description("VIP特典")]
# [MessagePackObject(True)]
@dataclass
class VipMB(MasterBookBase):
    # [Description("放置バトル経験値ボーナス(%)")]
    # [PropertyOrder(3)]
    AutoBattlePlayerExpBonus: int
    # [Description("VIPデイリー報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(26)]
    DailyRewardItemList: list[UserItem]
    # [Description("時空の洞窟コインドロップ増加​(%)")]
    # [PropertyOrder(9)]
    DungeonBattleCoinBonus: int
    # [Description("時空の洞窟ゴールドボーナス(%)")]
    # [PropertyOrder(10)]
    DungeonBattleGoldBonus: int
    # [Description("時空の洞窟：見逃し可能回数")]
    # [PropertyOrder(13)]
    DungeonBattleMissedCompensationCount: int
    # [Description("運命ガチャが可能か否か")]
    # [PropertyOrder(19)]
    IsDestinyGachaAvailable: bool
    # [Description("運命ガチャのログが見れるか否か")]
    # [PropertyOrder(20)]
    IsDestinyGachaLogAvailable: bool
    # [Description("研磨時にロックが可能か否か​")]
    # [PropertyOrder(23)]
    IsLockEquipmentTrainingAvailable: bool
    # [Description("祈りの泉一括派遣、受け取り​が可能か否か")]
    # [PropertyOrder(15)]
    IsMultipleBountyQuestAvailable: bool
    # [Description("ギルドレイドの一括掃討が可能か否か")]
    # [PropertyOrder(18)]
    IsMultipleQuickStartGuildRaidAvailable: bool
    # [Description("ボス/無窮の塔掃討が可能か否か")]
    # [PropertyOrder(21)]
    IsQuickBossBattleAvailable: bool
    # [Description("ギルドレイドの掃討が可能か否か")]
    # [PropertyOrder(17)]
    IsQuickStartGuildRaidAvailable: bool
    # [Description("神装強化の装備返還が可能か否か​")]
    # [PropertyOrder(22)]
    IsRefundEquipmentMergeAvailable: bool
    # [Description("ログインボーナス見逃し補填回数")]
    # [PropertyOrder(14)]
    LoginBonusMissedCompensationCount: int
    # [Description("VIPレベル")]
    # [PropertyOrder(1)]
    Lv: int
    # [Description("ボス/無窮の塔挑戦購入可能回数増加​")]
    # [PropertyOrder(11)]
    MaxBossBattleUseCurrencyCount: int
    # [Description("英雄枠数増加​")]
    # [PropertyOrder(8)]
    MaxCharacterBoxPlus: int
    # [Description("ギルドレイド挑戦可能回数")]
    # [PropertyOrder(16)]
    MaxGuildRaidChallengeCount: int
    # [Description("仮想通貨で高速周回できる回数")]
    # [PropertyOrder(5)]
    MaxQuickUseCurrencyCount: int
    # [Description("ショップの アイテム数増加​")]
    # [PropertyOrder(12)]
    MaxShopItemCountPlus: int
    # [Description("ソロクエストを挑戦できる回数")]
    # [PropertyOrder(6)]
    MaxSoloQuestCount: int
    # [Description("チームクエストを挑戦できる回数")]
    # [PropertyOrder(7)]
    MaxTeamQuestCount: int
    # [Description("高速戦闘経験値ボーナス(%)")]
    # [PropertyOrder(5)]
    QuickBattlePlayerExpBonus: int
    # [Description("VIP到達時報酬リスト")]
    # [Nest(False, 0)]
    # [PropertyOrder(24)]
    ReachRewardItemList: list[UserItem]
    # [Description("必要累計 VIP経験値")]
    # [PropertyOrder(2)]
    RequiredExp: int
    # [Description("VIPギフトリスト")]
    # [Nest(True, 0)]
    # [PropertyOrder(25)]
    VipGiftInfoList: list[VipGiftInfo]

# [Description("ワールドグループ")]
# [MessagePackObject(True)]
@dataclass
class WorldGroupMB(MasterBookBase, IHasStartEndTime):
    # [DateTimeString]
    # [Description("レジェンドリーグ終了日時")]
    # [PropertyOrder(9)]
    EndLegendLeagueDateTime: str
    # [Description("終了日時")]
    # [PropertyOrder(5)]
    EndTime: str
    # [Description("グランドバトル開始日時")]
    # [Nest(False, 0)]
    # [PropertyOrder(6)]
    GrandBattleDateTimeList: list[StartEndTime]
    # [DateTimeString]
    # [Description("レジェンドリーグ開始日時")]
    # [PropertyOrder(8)]
    StartLegendLeagueDateTime: str
    # [Description("開始日時")]
    # [PropertyOrder(4)]
    StartTime: str
    # [Description("タイムサーバー")]
    # [PropertyOrder(1)]
    TimeServerId: int
    # [Description("WorldIdのリスト")]
    # [PropertyOrder(3)]
    WorldIdList: list[int]

